//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredHack2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalCodeLatLong
    {
        public int Id { get; set; }
        public string PostalCode { get; set; }
        public float Lat { get; set; }
        public System.DateTime CacheDate { get; set; }
        public float Lng { get; set; }
    }
}
