//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredHack2015
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class stgDealer
    {
        [DisplayName("Brand")]
        public string BrandName { get; set; }
        [DisplayName("Dealer")]
        public string DealerName { get; set; }
        [DisplayName("Date Signed")]
        
        public Nullable<System.DateTime> SignedOn { get; set; }
        [DisplayName("Dealer Code")]
        public string DealerCode { get; set; }
        [DisplayName("Mfg Region")]
        public string ManfRegionCode { get; set; }
        [DisplayName("Address 1")]
        public string Address1 { get; set; }
        [DisplayName("Address 2")]
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        [DisplayName("Zip")]
        public string PostalCode { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public int id { get; set; }
    }
}
